version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: db-container
    restart: always

    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

    ports:
      - "5434:5432" 

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: